# Generated by Django 5.1.2 on 2025-06-22 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Price_one_month', models.IntegerField(max_length=10, null=True)),
                ('Price_three_month', models.IntegerField(max_length=10, null=True)),
                ('Price_six_month', models.IntegerField(max_length=10, null=True)),
                ('Price_yearly', models.IntegerField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Demo_Members_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=200)),
                ('Last_Name', models.CharField(max_length=200)),
                ('Age', models.IntegerField(max_length=10)),
                ('Mobile_No', models.IntegerField(max_length=10)),
                ('Height', models.IntegerField(max_length=10)),
                ('Weight', models.IntegerField(max_length=10)),
                ('Address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Members_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=200)),
                ('Last_Name', models.CharField(max_length=200)),
                ('Age', models.IntegerField(max_length=10)),
                ('Mobile_No', models.IntegerField(max_length=10)),
                ('Height', models.IntegerField(max_length=10)),
                ('Weight', models.IntegerField(max_length=10)),
                ('Address', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='APp1.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
